name: Sync with template

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: "CloudAstro/terraform-opentelekomcloud-module-template"
          upstream_branch: "main"
          source_gh_token: ${{ secrets.GITHUB_TOKEN }}
